version: '3.4'
services:
  rasa:
    image: rasa-server-okteto:latest
    build: "./"
    restart: always
    volumes:
    - ./data:/app/data
    - ./actions:/app/actions
    - ./tests:/app/tests
    command: bash -c "rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\" -p 8080 --debug"
    working_dir: "/app"
    ports:
    - '5005:8080'
    public: true
    networks:
    - all

  rasa-actions:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
    - ./actions:/app/actions
    command: bash -c "rasa run actions"
    working_dir: "/app"
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable.ipv6: "true"